### ISSUE TITLE
Uncaught ReferenceError: _getBrowser is not defined

### ISSUE THREAD

**Issue by Pollo00S** [castjs/castjs#34] opened 2022-08-21 11:54 UTC
Hi, after updating to 5.1.0, i'm getting this error on Firefox. Mb it could appear on unsupported browsers. (it does appear after few seconds)

![immagine](https://user-images.githubusercontent.com/40206145/185789530-e8a0e741-df8f-4506-bd9e-3cc94bc19709.png)
![immagine](https://user-images.githubusercontent.com/40206145/185789541-ec8c55a7-a992-4827-b80e-fc2ed831d321.png)

**Comment by Fenny** [comment] 2022-08-25 01:59
@Pollo00S thanks for reporting this error, it's caused by a type. It was missing the reference `this`.
Fixed in https://github.com/castjs/castjs/releases/tag/v5.2.0

Give it a couple of hours for cdnjs to update 👍

**Closed by Fenny** 2022-08-25 01:59 UTC
